# Generated by Django 5.0.3 on 2024-04-03 08:06

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None)),
                ('morning_start_time', models.TimeField(default=datetime.time(0, 0))),
                ('morning_end_time', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_start_time', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_end_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='departments_config.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_instructors', to='departments_config.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_rooms', to='departments_config.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('batch', models.PositiveIntegerField()),
                ('number_of_sections', models.PositiveIntegerField(default=1)),
                ('courses', models.JSONField()),
                ('instructors', models.JSONField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_years', to='departments_config.department')),
                ('rooms', models.ManyToManyField(related_name='department_year_rooms', to='departments_config.room')),
            ],
        ),
    ]
