# Generated by Django 5.0.3 on 2024-03-23 20:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None)),
                ('rooms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('morning_start_time', models.TimeField(default=datetime.time(0, 0))),
                ('morning_end_time', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_start_time', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_end_time', models.TimeField(default=datetime.time(0, 0))),
                ('courses', models.ManyToManyField(related_name='departments', to='departments_config.course')),
                ('instructors', models.ManyToManyField(related_name='departments', to='departments_config.instructor')),
            ],
        ),
    ]
