# Generated by Django 5.0.3 on 2024-04-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reserved',
        ),
    ]
