# Generated by Django 5.0.3 on 2024-04-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0002_instructorcourse_alter_departmentyear_instructors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='instructorcourse',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='singlecourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='DepartmentYear',
        ),
        migrations.DeleteModel(
            name='InstructorCourse',
        ),
        migrations.DeleteModel(
            name='SingleCourse',
        ),
    ]
