# Generated by Django 5.0.3 on 2024-04-04 09:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0003_remove_instructorcourse_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_days', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('reserved_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_rooms', to='departments_config.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments_config.room')),
            ],
        ),
    ]
