# Generated by Django 5.0.3 on 2024-04-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0004_reservedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='departments_config.room'),
        ),
    ]
