# Generated by Django 5.0.3 on 2024-04-04 08:02

import django.db.models.deletion
import scheduling_config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments_config', '0003_remove_instructorcourse_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('batch', models.PositiveIntegerField()),
                ('number_of_sections', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_years', to='departments_config.department')),
                ('rooms', models.ManyToManyField(related_name='scheduling_rooms', to='departments_config.room')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_durations', models.JSONField(validators=[scheduling_config.validators.validate_time_durations_data])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_courses', to='departments_config.course')),
                ('instructors', models.ManyToManyField(related_name='scheduling_instructors', to='departments_config.instructor')),
                ('scheduling_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_courses', to='scheduling_config.schedulingdata')),
            ],
        ),
    ]
