# Generated by Django 5.0.3 on 2024-04-13 17:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('batch', models.PositiveIntegerField()),
                ('number_of_sections', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_years', to='departments_config.department')),
                ('rooms', models.ManyToManyField(related_name='scheduling_rooms', to='departments_config.room')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_durations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_courses', to='departments_config.course')),
                ('instructors', models.ManyToManyField(related_name='scheduling_instructors', to='departments_config.instructor')),
                ('scheduling_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_courses', related_query_name='all_courses', to='scheduling_config.schedulingdata')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheduling_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling_config.schedulingdata')),
            ],
        ),
    ]
