# Generated by Django 5.0.3 on 2024-04-12 06:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingcourse',
            name='time_durations',
        ),
        migrations.AddField(
            model_name='schedulingcourse',
            name='time_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='schedulingcourse',
            name='scheduling_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_courses', related_query_name='all_courses', to='scheduling_config.schedulingdata'),
        ),
    ]
