# Generated by Django 5.0.3 on 2024-04-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0001_initial'),
        ('scheduling_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingcourse',
            name='rooms',
            field=models.ManyToManyField(related_name='scheduling_courses', to='departments_config.room'),
        ),
        migrations.AlterField(
            model_name='schedulingcourse',
            name='instructors',
            field=models.ManyToManyField(related_name='scheduling_courses', to='departments_config.instructor'),
        ),
    ]
