# Generated by Django 5.0.3 on 2024-04-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_config', '0002_remove_room_reserved'),
        ('scheduling_config', '0002_schedulingcourse_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_instructors', to='departments_config.instructor')),
                ('scheduling_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_instructors', to='scheduling_config.schedulingdata')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_instructors', to='scheduling_config.section')),
            ],
        ),
        migrations.AddField(
            model_name='schedulingcourse',
            name='section_instructors',
            field=models.ManyToManyField(related_name='scheduling_courses', to='scheduling_config.schedulinginstructor'),
        ),
    ]
