# Generated by Django 5.0.3 on 2024-04-12 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_config', '0002_remove_schedulingcourse_time_durations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingcourse',
            name='time_durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
