# Generated by Django 5.0.3 on 2024-04-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_config', '0003_schedulingcourse_time_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingcourse',
            name='time_duration',
        ),
    ]
