# Generated by Django 5.0.3 on 2024-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_config', '0003_schedulinginstructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulinginstructor',
            name='section',
        ),
        migrations.AddField(
            model_name='schedulinginstructor',
            name='sections',
            field=models.ManyToManyField(related_name='scheduling_instructors', to='scheduling_config.section'),
        ),
    ]
