# Generated by Django 3.2.7 on 2024-03-05 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(blank=True, related_name='instructors', to='schedule.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None)),
                ('morning_start_time', models.TimeField(auto_now_add=True)),
                ('morning_end_time', models.TimeField(auto_now_add=True)),
                ('afternoon_start_time', models.TimeField(auto_now_add=True)),
                ('afternoon_end_time', models.TimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='departments', to='schedule.Course')),
                ('instructors', models.ManyToManyField(blank=True, related_name='departments', to='schedule.Instructor')),
            ],
        ),
    ]
