# Generated by Django 5.0.3 on 2024-04-03 08:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('LECTURE', 'Lecture'), ('BREAK', 'Break')], max_length=20)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=20)),
                ('room', models.CharField(max_length=255)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments_config.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='departments_config.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments_config.instructor')),
            ],
        ),
    ]
