# Generated by Django 5.0.3 on 2024-04-13 17:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments_config', '0001_initial'),
        ('scheduling_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='departments_config.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='departments_config.instructor')),
                ('parent_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='scheduling_config.schedulingdata')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='departments_config.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='scheduling_config.section')),
            ],
        ),
    ]
