# Generated by Django 5.0.3 on 2024-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='temp_section',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
