# Generated by Django 5.0.3 on 2024-04-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_scheduleentry_temp_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='section',
        ),
    ]
