# Generated by Django 5.0.3 on 2024-04-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_scheduleentry_section'),
        ('scheduling_config', '0002_schedulingcourse_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='section',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='related_schedules', to='scheduling_config.section'),
            preserve_default=False,
        ),
    ]
